# Generated by Django 4.2.16 on 2024-10-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_photo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='all_files',
            field=models.FileField(default=111, upload_to='zips/'),
            preserve_default=False,
        ),
    ]
